spring:
  application:
    profiles:
      active: production
    name: card-service
  config:
    import: optional:configserver:http://localhost:9888
logging:
  level:
    org.springframework: info
server:
  address: 0.0.0.0
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: "health,refresh,env,info,metrics,prometheus"
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true

