spring:
  application:
    name: card-service
logging:
  level:
    org.springframework: info
server:
  address: 0.0.0.0
  port: 9080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



