spring:
  application:
    name: user-service

logging:
  level:
    org.springframework: info

server:
  address: 0.0.0.0
  port: 9082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true


